name: Universal workflow
on:
  push:
    branches-ignore: []
    tags-ignore: ['**']

jobs:
  sanity-check:
    name: ğŸ‘€ Sanity check
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@v3
      - name: ğŸ—ï¸ Setup Job
        uses: ./.github/actions/setup

      - name: ğŸ›  Build
        run: yarn build
      - name: ğŸ’… Lint
        run: yarn lint --verbose
      - name: ğŸ›  Test
        run: yarn test
